ecomfe/zrender

- src/macro.js
考虑到全局函数问题以及fecs代码规范问题，放弃EC_DEFINED、EC_NOT_DEFINED等形式。
将宏函数封装到zrender/macro下，使用方式：
```javascript
// 宏模块的名称可以不用限制为`macro`
// 在zrender中也可以用相对位置`./macro`、`../macro`等
var macro = require('zrender/macro');
if (macro.isDefined('debugMode') && macro.isDefined('mobile')) {
console.log('xxxx');
}
```
echarts-optimizer分析文件时，由上往下查找宏模块的声明`var macro = require('zrender/macro')`，找到后，则设置当前宏模块名称为`macro`，继续往下找出`if(macro.isDefined('xxx')) {...}`等宏调用，比较一下宏调用所属的对象名称与当前的宏模块名称，如果一致，则计算if表达式的值，true则保留if分支下的BlockStatement，false则保留else分支下的BlockStatement。
_注意：先声明再调用，否则ast分析不出来。_
> 将宏函数移到zrender上

- src/contain/path.js
> Fix left side of rect not contained.

- src/core/PathProxy.js
在不支持setLineDash方法的浏览器中，_dashedLineTo方法原先的循环条件在绘制x坐标相同的线时会陷入死循环。
> 修复当起始结束点x坐标相同时，_dashedLineTo方法陷入死循环

- src/Layer.js
[ECharts allows](https://github.com/ecomfe/echarts/blob/31c35216b64ea5b9397829aefe57b8a1bc185e20/src/echarts.js#L1933) the user to supply a custom method to be used whenever a canvas is created. It does so by overriding `util.createCanvas`. This change makes the canvas `Layer` use `util.createCanvas` so the ECharts users can supply a custom canvas creation method.
> use overridable util.createCanvas for Layer canvas

- src/Painter.js
`zlevel` is limited to `EL_AFTER_INCREMENTAL_INC` or `0`.
I wonder whether it's designed or a bug.
正好用到了正负多层zlevel，发现异常。不知道这里是加了incremental之后的特殊处理还是bug……
> Fix zlevel bug

- src/graphic/helper/image.js
Handle non-existing image by clearing `pending` in `globalImageCache` for image `onerror`
See Issue https://github.com/ecomfe/zrender/issues/339
> Fix memory leak due to non-existing image rendering

- src/graphic/helper/text.js
#379 is introduced in this commit: https://github.com/ecomfe/zrender/commit/6253c14e9c3df1d5c0a3785c607d92464057c956 .
Not sure what's wrong in the commit, but this PR resolved the bug.
@100pah Please have a look and review the code. Thanks!
> fix: text opacity bug #379

- src/svg/graphic.js
Fix the bug apache/incubator-echarts#9826 .
This was caused by an ad hoc method (by setting fill="rgba(0,0,0,0.002)" for transparent elements) for an SVG bug on Chromium.
Since it has been fixed more than a year, this is no longer needed.
See more: https://bugs.chromium.org/p/chromium/issues/detail?id=659790
> fix(svg): remove ad hoc fix of an SVG fill bug

- src/contain/text.js
- src/graphic/Displayable.js
- src/graphic/helper/text.js
- src/svg/graphic.js
- src/vml/graphic.js
Add an approach to customize the inerpretation of `textPosition` for some shape like 'pin', 'flag', whose center is not exactly `[w / 2, h / 2]`.
> Support `calculateTextPosition ` for some custom shape.

- src/svg/graphic.js
- test/svg-arc.html
It fixes the bug with arc `large` value whose `endAngle` is greater than `Math.PI * 2`. It fixes and closes #496.
---
Canvas result of `text/svg-arc.html` (SVG is expected to be the same): 
The number in the circle represents the `(i, j)` value, and the circles are of `startAngle` to be `Math.PI / 4 * i` and `endAngles` to be `Math.PI / 4 * j`.
Before this fix, the SVG result is (wrong parts are highlighted with blue):
This is mainly because the `large` calculation was wrong with `endAngle - startAngle` larger than `Math.PI * 2`.
---
After this fix, the SVG result is (difference with the Canvas result is in blue):
I think currently the SVG result is correct, although we cannot say it's a bug with Canvas. Maybe we should adjust the behavior of Canvas cases.
[The Canvas …
> fix(svg): arc large bug #496

- src/Painter.js
IOS13 safari probably has a compositing bug (z order of the canvas and the consequent
dom does not act as expected) when some of the parent dom has
`-webkit-overflow-scrolling: touch;` and the webpage is longer than one screen and
the canvas is not at the top part of the page.
Check `https://bugs.webkit.org/show_bug.cgi?id=203681` for more details. We remove
this `overflow:hidden` to avoid the bug.
> fix: ios13 safari z order bug.

- src/svg/Painter.js
- src/svg/helper/ShadowManager.js
There are two fixes in this pull request
1. Shadow is affected on the text, not main element. Like the shot below
This bug is caused by https://github.com/ecomfe/zrender/commit/409d52619f8a68807658b00cc53d91c6ce63de4d#diff-4bf718158d3bfa56f864a33987f9882aL238
shadow should be added on the `svgElement` instead of `prevSvgElement`, which can be the text element.
2. DOM of shadow is stored in the `style` property of SVG. And this `style` property can be replaced during the update of echarts. It will cause  this information lost and can't remove the `filter` attribute successfully in https://github.com/ecomfe/zrender/blob/master/src/svg/helper/ShadowManager.js#L123
So I fixed it by putting the DOM in `displayable` insteadof `style`.
> Fix shadow display bug on SVG. 

- src/contain/text.js
- src/svg/graphic.js
fix: fix text cache bug in SVG, which is brought by commit, which is brought by commit 61a0d3d0bb79977064e3b406732b09b2a3b333ab
Use `echarts/test/treemap-simple.html` to test it please (where text truncate is used):
Steps:
(1) Zoom in util some text disappear.
(2) Zoom out, the text should be able to display again.
> fix: fix text cache bug in SVG, 

- src/svg/Painter.js
- src/svg/graphic.js
Fix https://github.com/apache/incubator-echarts/issues/11543 .
This commit can remove the text. But when the mouse hovers on the circle again, the text doesn't show up.
> WIP(svg): clear text when mouse leaves

- src/Handler.js
- src/core/event.js
- src/dom/HandlerProxy.js
- src/mixin/Draggable.js
- src/mixin/Eventful.js
[Page Event]
"page events" are `pagemousemove` and `pagemouseup`.
They are triggered when a user pointer interacts on the whole webpage
rather than only inside the zrender area.
The use case of page events can be, for example, if we are implementing a dragging feature:
```js
zr.on('mousedown', function (event) {
var dragging = true;
// Listen to `pagemousemove` and `pagemouseup` rather than `mousemove` and `mouseup`,
// because `mousemove` and `mouseup` will not be triggered when the pointer is out
// of the zrender area.
zr.on('pagemousemove', handleMouseMove);
zr.on('pagemouseup', handleMouseUp);
function handleMouseMove(event) {
if (dragging) { ... }
}
function handleMouseUp(event) {
dragging = false; ...
zr.off('pagemousemove', handleMouseMove);
zr.off('pagemouseup', handleMouseUp);
} …
```
> support page event.

- src/svg/graphic.js
The parentNode in https://github.com/ecomfe/zrender/pull/542/files#diff-5bb01bd8925bd801f17e33bdb859d019R516 may be null if the element is removed in https://github.com/ecomfe/zrender/blob/svg-fix-text-remove-error/src/svg/Painter.js#L205
> fix(svg): fix removing el may have error when text is set to none

- src/Handler.js
- src/core/env.js
- src/core/event.js
- src/dom/HandlerProxy.js
- src/mixin/Draggable.js
- src/mixin/Eventful.js
- src/zrender.js
This pull request is in the type of:
The original merged PR is #536 and apache/incubator-echarts#11710 .
But here we make some changes now.
[Drag outside]:
That is, triggering `mousemove` and `mouseup` event when the pointer is out of the
zrender area when dragging. That is important for the improvement of the user experience
when dragging something near the boundary without being terminated unexpectedly.
We originally consider to introduce new events like `pagemovemove` and `pagemouseup`
to resolve this issue. 
Previously we provide "page event" in #536. 
But after further thinking, I think the the new way below is better.
Some drawbacks of it is described in
<https://github.com/ecomfe/zrender/pull/536#issuecomment-560286899>
Instead, we referenced the specifications: …
> enhancement of mouse event in dragging.

- src/mixin/Draggable.js
This is a pull request about adding dragging support to the group elements.
It will find if any ancestor is set `draggable` and apply `drift` on it.
> support draggable on group

- src/graphic/helper/subPixelOptimize.js
The interface `subPixelOptimize` should not make users consider `style.lineWidth`.
Should be:
```js
new Rect({
subPixelOptimize: true
})
```
related: apache/incubator-echarts#11874 apache/incubator-echarts#11891
related PR: https://github.com/apache/incubator-echarts/pull/11991
> fix: fix subpixel optimize with no lineWidth

- src/core/dom.js
- src/core/event.js
- src/core/fourPointsTransform.js
- src/dom/HandlerProxy.js
- test/css-transform-inverse.html
It usually use on the case: 
We have `[zrX, zrY]`. we want to get the corresponding `[left, top]` of another DOM element (for example, `document.body`, or vise versa.
It can be used on the positioning of echarts tooltip which is appended to `document.body`.
> feature: support convert between two local DOM coord. And some refactor.

- src/svg/Painter.js
See https://github.com/apache/incubator-echarts/pull/12144 for details.
> Fix 11781: save svg image with toolbox

- src/svg/helper/ClippathManager.js
This reverts commit 2639dcef6961a6a613a993d8b80e32082b8b262a, which will cause clipping failue in main browsers.
> Revert "fix(svg): use lower case for clippath"

- src/graphic/Text.ts
This PR related to https://github.com/apache/incubator-echarts/pull/12947
Left padding in not working in rich mode
> Rich text padding

- src/canvas/Painter.ts
Before: hover layer is always created for all charts.
After: hover layer is only created when there is elements in hover layer.
> fix(hover): hover layer should be created only if having hover elements

- src/Element.ts
- src/animation/requestAnimationFrame.ts
- src/config.ts
**1) Fix incorrect logic of `requestAnimationFrame`.**
There is a flaw in the judgment about `requestAnimationFrame`.
**2) Make `devicePixelRatio` compatible with IE8/9/10.**
IE which has a version small than 11 has no `window.devicePixelRatio`, but can be calculated by
```js
window.screen.deviceXDPI / window.screen.logicalXDPI
```
**3) Don't call `Object.defineProperty` in IE8.**
Although IE8 has the method `Object.defineProperty`, it's only supported on DOM objects and with some non-standard behaviors.
> Reference: [Internet_Explorer_8_specific_notes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Internet_Explorer_8_specific_notes)
> fix: fix compatibility in IE and logic flaw of `requestAnimationFrame`.

- src/canvas/graphic.ts
- src/graphic/helper/dashStyle.ts
- src/svg/graphic.ts
Related to apache/incubator-echarts#12961
> feat: normalize dash style in zrender.

- src/zrender.js
change 'handerProxy' to 'handlerProxy' for unified reason.
> Typo fix for zender.js

- src/graphic/helper/roundSector.ts
- src/graphic/shape/Sector.ts
For the PR on ECharts apache/incubator-echarts#13378
> feat(shape/sector): support cornnerRadius & innerCornerRadius.

- src/tool/color.ts
- test/ut/spec/tool/color.test.ts
(1) add fallback for `rgba(r, g, b)`. It will be converted to `rgba(r, g, b, 1)`.
(2) support 8-digit hex color(`#rrggbbaa`) which uses the last pair of digits as alpha, see https://drafts.csswg.org/css-color/#hex-notation and also support the form of `#rgba` (4-digit hex color in the form of `#rgba`).
(1) `rgba(17, 163, 69)` will be converted to `[17, 163, 69, 1]` **(Previous result is `undefined`)**
(2) `#14c4baff` will be converted to `[20, 196, 186, 1]` **(Previous result is `undefined`)**
(3) `#07f0` will be converted to `[0, 119, 255, 0]` **(Previous result is `undefined`)**
This fixes apache/incubator-echarts#13433 and enables the forms of color to be more flexible.
Please refer to `test/ut/spec/tool/color.test.ts`
> fix(tool/color): enhance the color compat.

- src/graphic/helper/roundSector.ts
- test/sector.html
When the corner radius is specified but the angle of sector is smaller than `1e-4`, we should not draw the corners.
Otherwise, we will get an unexpected result like the following screenshots.
> fix(sector): skip drawing corner radius if no arc.

- src/core/Transformable.ts
fix: Fix transform, which previously get wrong result. 
(see https://github.com/ecomfe/zrender/commit/cef72d0ebb709c967ffc5b32d910abee07299e9f#diff-f01f52eff1e36b4bd3e27c19cda9e238dd8f35b03157e53b70de5d2588c630ddR183 ).
> Fix/transform setLocalTransform

- src/animation/Animation.ts
make manually update animation not trigger "frame" callback,
otherwise it make cause dead loop if manual update calling is from one of the "frame" callback.
> fix: make manually update animation not trigger "frame" callback

- src/svg/graphic.ts
- test/svg-image-opacity.html
To fix the bug reported in apache/incubator-echarts#13762. (`opacity` is not working in SVG renderer)
Please refer to `test/svg-image-opacity.html` for the test case.
**Before**
**After**
> fix(svg/image): fix `opacity` is not working in SVG renderer.

- src/svg/graphic.ts
Related source code in ECharts: http://github.com/apache/incubator-echarts/tree/master/src/chart/heatmap/HeatmapLayer.ts
**The broken heatmap layer**
**After fix**
**The related test case can be found in `echarts/test/heatmap-map.html`**
> fix(image): svg image src may be a canvas element.

- src/Storage.ts
- src/canvas/Painter.ts
- src/canvas/graphic.ts
- src/graphic/IncrementalDisplayable.ts
- src/svg/graphic.ts
- src/zrender.ts
Remove unexpected imports from exports. Which may lead to bundling the whole lib in echarts.
> fix: remove unexpected imports from exports .

- src/config.ts
- enhance ecomfe/zrender#623
-  fix apache/incubator-echarts#13940.
As reported in apache/incubator-echarts#13940, WeChat MiniProgram has no `screen` object in the global `window` object so that it may throw an unexpected error.
> fix(config): check if window.screen exists before calculating the dpr.

- package.json
- src/tool/parseSVG.ts
This PR includes two changes.
1. export parseXML in parseSVG to avoid breaking change
2. change `build:esm` command to `build:lib` to be consistent with echarts
> fix: export parseXML in parseSVG to avoid breaking change

- src/Handler.ts
- src/core/types.ts
- src/dom/HandlerProxy.ts
fix https://github.com/apache/incubator-echarts/issues/13958
This bug is brought when fixing the wrong `mouseout` event triggered in SVG renderer in https://github.com/ecomfe/zrender/compare/fix-global-out?expand=1#diff-619a90e06ad2f3966dac739e2d1fb17006d9f44978316c758d694a40cde28201L222
But in canvas renderer, the `event.target` will is the canvas element when mouseout. Not the viewport. So the `globalout` will never be triggered.
Determine if the target element is a descendant of the viewport. If so, both `mouseout` and `globalout` event won't be triggered.
> fix(handler): fix global out not work bug. 

- src/graphic/helper/roundSector.ts
- fix apache/echarts#14074: Sector blink when zero data exists.
> fix(sector): set `arc` as 0 if `startAngle` equals `endAngle`, skip the normalization.

- src/PainterBase.ts
- src/svg/Painter.ts
- src/svg/graphic.ts
- src/svg/helper/PatternManager.ts
- src/svg/helper/ShadowManager.ts
(1) The declaration of method `getViewportRoot` in https://github.com/ecomfe/zrender/blob/master/src/PainterBase.ts#L24 is the same as https://github.com/ecomfe/zrender/blob/master/src/PainterBase.ts#L31
It may have been unexpectedly brought in the merging process. So removed it.
(2) remove/comment some other redundant or unused variables and imports.
> fix(svg): remove redundant declarations.

- src/canvas/Painter.ts
fix apache/echarts#14112
The variable `ctx` should be fetched after `initContext` invoked, otherwise, it will be always `null`.
> fix(canvas/painter): ctx was mistakenly assigned with a null value.

- src/graphic/helper/parseText.ts
The definition of `parsePercent` in [contain/text.ts#parsePercent](https://github.com/ecomfe/zrender/blob/master/src/contain/text.ts#L138-L146) (exported) is the same as [graphic/helper/parseText.ts#parsePercent](https://github.com/ecomfe/zrender/blob/master/src/graphic/helper/parseText.ts#L744-L752) (unexported)
So removed it.
And commented on the temporary unused code.
> fix(graphic/parseText): remove redundant `parsePercent` function definition

- src/export.ts
- src/graphic/CompoundPath.ts
- src/graphic/Image.ts
- src/graphic/TSpan.ts
- src/graphic/shape/Arc.ts
- src/graphic/shape/BezierCurve.ts
- src/graphic/shape/Circle.ts
- src/graphic/shape/Droplet.ts
- src/graphic/shape/Ellipse.ts
- src/graphic/shape/Heart.ts
- src/graphic/shape/Isogon.ts
- src/graphic/shape/Line.ts
- src/graphic/shape/Polygon.ts
- src/graphic/shape/Polyline.ts
- src/graphic/shape/Rect.ts
- src/graphic/shape/Ring.ts
- src/graphic/shape/Rose.ts
- src/graphic/shape/Sector.ts
- src/graphic/shape/Star.ts
- src/graphic/shape/Trochoid.ts
See detail https://github.com/ecomfe/zrender/issues/682
> feat: TS type export (#682)

- src/canvas/graphic.ts
- src/graphic/Text.ts
If we set an invalid value on `ctx.globalAlpha`. It will take no effect and keep the previous value, which will cause `opacity` value leaks between displayables.
In some cases of ECharts. The value will exceed the range `0 ~ 1`, which usually happens when using `visualMap`. It's also invalid and a better and more intuitive way is to clamp the value to `0 ~ 1`
> fix(render): fix illegal opacity may lead to opacity leak.

- .github/workflows/nightly.yaml
- build/build.js
- build/prepareNightly.js
- package.json
It will publish a dev version in format `5.0.4-dev.2021.04.16` from master  to `zrender-nightly@dev` at 08:00 UTC every day.
> chore: add nightly build action to workflow

- src/core/BoundingRect.ts
fix apache/echarts#14534
**PENDING:**
It seems `Infinity` cannot be simply considered as `0`, after all, it's infinitely large but not zero.
And I saw the `BoundingRect#union` is checking if the value is finite, which indicates the infinite values can exist in the constructed instance of `BoundingRect`, so I'm thinking the no check need to do in the constructor.
> fix(BoundingRect): don't check if the width and height is finite in constructor.

- build/prepareNightly.js
Previously the major, minor, and patch in the dev version are the same as the last stable version, which is wrong in semver. So this PR increases the patch version automatically when publishing the dev version. For example, the current stable version is `5.1.0`. Then the dev version will be `5.1.1-dev.20210420`. It's not fully correct because the next stable version maybe 5.2.0. But I think it won't have any bad effect.
> chore: increase dev version from stable version.

- .github/workflows/nightly.yaml
Use the latest tag instead of dev in zrender-nightly or if it's always being the first published version
> chore: use latest tag in zrender-nightly

- src/core/Transformable.ts
- src/tool/parseSVG.ts
- test/transform.html
1. Add property `skewX`, `skewY` in Transformable
2. Support decompose matrix with skew.
3. Parse `skewX` `skewY` in SVG transform attributes.
This PR also did some performance optimization on the transform calculation.
TODO Note:
zrender uses a different hand coordinate system compared to CSS transform. It may confuse developers when using `rotation`, `skewX`, `skewY`. But change them will break a lot of codes. I guess we can only accept it in a very long time.
Related issues:
https://github.com/apache/echarts/issues/14703
> feat: support skew in transform and svg parser

- src/core/Transformable.ts
- test/origin.html
Previously when calculating skew `getLocalTransform`. `origin` is not considered.
Here is the new added detailed test case
> fix skew transform with origin.

- src/core/PathProxy.ts
- src/graphic/Path.ts
- test/segmentIgnoreThreshold.html
Before:
After:
Fix https://github.com/apache/echarts/issues/14949
> fix small subpath may be ignored when optimizing small line segments

- src/canvas/Layer.ts
- src/canvas/Painter.ts
- src/canvas/graphic.ts
- src/export.ts
- src/graphic/Path.ts
- src/graphic/Pattern.ts
- src/svg/helper/PatternManager.ts
fixes apache/echarts#14953
1) make `type`, `svgElement`, `svgWidth`, `svgHeight` of `PatternObject ` optional.
2) fixed some type issues.
> fix(pattern): remove non-required properties from PatternObject and fix some type issues.

- .github/workflows/nightly.yaml
add workflow dispatch to publish nightly build if it fails.
> chore: add workflow dispatch

- src/canvas/Painter.ts
Fix https://github.com/apache/echarts/issues/15005 . Potential memory leak is also avoided.
> fix(canvas): fix extra save caused in dirty rect.

- src/graphic/Text.ts
fix the Echart's issue:
https://github.com/apache/echarts/issues/15165
https://github.com/apache/echarts/issues/15077
---
with the following config:
```javascript
legend: {
left: 'center',
top: 'center',
data:[
'GoogleMaps','Facebook','Youtube','Google+','Weixin',
'Twitter', 'Skype', 'Messenger', 'Whatsapp', 'Instagram'
],
textStyle: {
lineHeight: 100,
},
},
```
Before fixed, `legend.textStyle.lineHeight` is not working.
After fixed:
> fix: legend text.lineHeight option not work

- src/tool/morphPath.ts
- src/tool/path.ts
In this PR I changed the hash algorithm in subpath sorting from [z-order](https://en.wikipedia.org/wiki/Z-order_curve) to [hilbert](https://en.wikipedia.org/wiki/Hilbert_curve). The difference is subtle in most cases. But in several cases, paths may move across a long distance to another even though they don't need it.  That's because two points may cross the whole dim when they are still adjacent on z-order. But hilbert won't have this issue.
> optimize subpath sorting in combine / spearate morph.

- src/canvas/graphic.ts
To resolve apache/echarts#15238.
Because unexpected value `null` or `'none'` is assigned to `ctx.strokeStyle` or `ctx.fillStyle`, the Firefox devtools will print lots of annoying CSS warnings.
> fix(canvas): fix unexpected `none` or `null` value for ctx.strokeStyle & ctx.fillStyle

- src/svg/Painter.ts
- src/svg/core.ts
- src/svg/graphic.ts
- src/svg/helper/ClippathManager.ts
- src/svg/helper/ShadowManager.ts
1) fix apache/echarts#15023, rect path can't be closed.
2) fix apache/echarts#15029 normalize color when using SVG renderer to support more cases, for example, some tools/platforms can't recognize the alpha in color. See the screenshot below.
3) fix eslint error about `for-in`.
PPT
There is another related issue apache/echarts#15064, I have no good and easy idea about it currently.
> fix(svg): fix rect path can't be closed bug & normalize color when using SVG renderer to support more cases.

- src/graphic/Text.ts
https://github.com/ecomfe/zrender/blob/master/src/graphic/Text.ts#L748-L752
> fix(text): fix a typo. `getStroke` should be `getFill`.

- src/core/PathProxy.ts
- src/svg/core.ts
1. Fix small line segment is drawn wrong when with other path primitives like `bezierCurve` brought in #760 . The pending line segment should be drawn before drawing other types of primitives. Fix https://github.com/apache/echarts/issues/15380
2. Fix normalizeColor throw error when using a gradient as color in SVG brought in #767
> fix several render bugs.

- src/core/matrix.ts
tsc complains about the return type of function invert with **strictNullChecks** enabled.
The return type is altered to a union type.
Typescript version: 4.3.4
> fix(matrix): union return type for function invert

- src/tool/parseSVG.ts
Resolves apache/echarts#15597
The [`image`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image) element in SVG support both `xlink:href` attribute and `link` attribute. [`xlink:href`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) seems not recommended anymore. But at least, we should consider supporting the `link` attribute.
> fix(svg): SVG <image> tag also should consider `href` attribute.

- src/svg/graphic.ts
Fix illegal value for the `stroke-dasharray` attribute.
Additionally, use the `opacity` attribute instead of CSS style property to enhance the compatibility.
> fix(svg): fix illegal value for `stroke-dasharray` attribute.

- src/core/event.ts
- src/svg/helper/ShadowManager.ts
Fix apache/echarts#15646
Fix apache/echarts#15697
It seems the `layerX/layerY` is unexpected in the case where the chart uses SVG renderer and has shadow filter.
From the above picture, we can see that the values of `layerX/layerY`(unexpected) are not the same as `offsetX/offsetY`(expected) and don't look like the offset relative to the "closest positioned element". (I couldn't know the reason)
According to [CANIUSE](https://caniuse.com/?search=offsetX) and the [release note](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/39) of Firefox, the `offsetX` and `offsetY` have been supported since desktop Firefox 39 
> Support for MouseEvent.offsetX and MouseEvent.offsetY have been added on desktop (bug 69787, but not on Firefox for Android or Firefox OS (they will be added in …
> fix(svg): svg mouse event doesn't work normally in Firefox when using shadow.

- src/export.ts
Export Displayable so it can be used for type annotation, especially in the case below
```ts
import * as zrender from 'zrender'
function (g: zrender.Group) {
g.eachChild((el: zrender.Displayable) => { /* do something */ })
}
```
> fix: export Displayable for type annotation compatibility

- src/graphic/shape/Circle.ts
The original logic is too tricky and may still break when autoBatch is enabled. So in this PR I changed to always close the path.
Before
After
> fix: always close path on circle

- src/core/arrayDiff.ts
- src/svg/graphic.ts
Currently, we are using an O(ND) diff algorithm(Myers' Diff Algorithm) in the SVG renderer. But when we do first render or clear all things on canvas. The complex becomes O(N2) because the difference is the whole N. Which will cause a significant performance drop. Especially we can't avoid the first render. So in this PR, I did a simple optimization to handle these two cases. The time of the first frame render comes down to 100ms from the terrible 3000ms for 10k objects.
Also, I found an existing bug that appears after the change in https://github.com/ecomfe/zrender/pull/829 and fixed it.
> fix: optimize arraydiff perf in first render and clear

- src/graphic/helper/parseText.ts
Hi, I'm doing a small project and noticed that in TextStyleProps we have `overflow?: 'break' | 'breakAll' | 'truncate' | 'none'`. The 'break' should break by word and it is, but not in all cases. 
There is a list of unicode characters divided into blocks (https://en.wikipedia.org/wiki/List_of_Unicode_characters) and zrender only considers Latin characters in the range from 33 to 255 which is 1st and 2nd block. Many European characters are in the 3rd block (Latin Extended-A https://en.wikipedia.org/wiki/Latin_Extended-A). 
Adding the 3rd UNICODE block should not cause any trouble (there are no characters that can be considered 'special') and would help a lot in using European languages because now some words are breaking in half :(
> Expanded UNICODE range for Latin characters  from 33-255 to 33-383 

- src/canvas/graphic.ts
- test/pattern-transform.html
> fix(pattern): fix matrix order & fix pattern create failed error

- src/svg/Painter.ts
- src/svg/core.ts
- src/svg/patch.ts
The initial [`_svgDom`](https://github.com/ecomfe/zrender/blob/next/src/svg/Painter.ts#L73) will be removed and replaced by the newly generated element after the [patch](https://github.com/ecomfe/zrender/blob/next/src/svg/patch.ts#L344) process so that all next operations on the old `_svgDom` won't work, e.g. `resize`, `innerHTML`, `clear`.
> fix(svg): update `_svgDom` when vnode changed.

- src/svg/Painter.ts
- src/svg/patch.ts
Fix a bug brought in #853. After the patch, No XML NS attributes were set on the `svg` DOM because of the same attributes in vnode.
So here we set attributes for `svg` dom when initializing.
> fix(svg): set attributes for svg dom when initializing.

- src/animation/requestAnimationFrame.ts
- src/config.ts
- src/core/env.ts
- src/svg/Painter.ts
- src/svg/helper.ts
- test/svg.html
This PR enables the SVG renderer to export base64-encoded dataURL instead of only the URL-encoded UTF-8 string.
> feat(svg): support exporting base64-encoded dataURL.

- src/Element.ts
As @plainheart pointed out in https://github.com/apache/echarts/pull/16225#issuecomment-998492571 . The looped keyframe animation may have conflict with the state transition animation. Because in the logic of handling state transition, the final frame of other animators will also be considered. But it's meaningless in a looped animation because it doesn't have final frame.
This PR fixes it by ignoring the loop animators. It's not perfect, we still have more things to do to deal with the keyframe animation combined with state transition. For example, how should the animation performs when keyframe animation and state transition both animated on the opacity. But this fix is simple and do well enough on most cases. So I proposed it before we rethinking the relationships of different …
> fix(animation): ignore loop animation when switching state.

- src/svg/graphic.ts
- test/svg-ssr.html
Fix https://github.com/apache/echarts/issues/16127#issuecomment-996208047
> fix: optimize image type check in the svg renderer.

- src/svg/Painter.ts
- src/svg/core.ts
Add new `useViewBox` opts in `renderToString` to make generated SVG responsive. See https://github.com/apache/echarts/issues/16127#issuecomment-983514232
> feat(ssr): add useViewBox opt

- src/svg/graphic.ts
If we apply an animation on 'style.strokePercent' from 0 to 1, the shape won't be drawn completely using SVG renderer.
This problem can be reproduced. You can reference https://codesandbox.io/s/condescending-mclaren-qrhdx?file=/src/App.js . If you click 'Restart Stroke Percent Animation' a few times, you'll see different results.
> fix(svg): fix animation on strokePercent will cause partially drawing.

- src/animation/Animator.ts
Currently `NaN` is being unexpectedly considered as the number type. It brings some bugs to animation.
Fix apache/echarts#16341
Please refer to the last test case in [`test/pie-animation.html`](https://github.com/apache/echarts/blob/next/test/pie-animation.html)
|  Before   | After  |
|  :----:  | :----:  |
| ![bug](https://user-images.githubusercontent.com/26999792/148653471-ab5faf47-659c-43f7-9703-502d284b42f8.gif) | ![right](https://user-images.githubusercontent.com/26999792/148653482-c32162bb-b896-4c17-b948-602b73a0d40d.gif) |
> fix(animator): `NaN` shouldn't be considered as the number type.

- src/graphic/helper/roundSector.ts
- test/sector.html
> fix(sector): don't use `normalizeArcAngles` anymore.

- src/Storage.ts
- src/svg-legacy/Painter.ts
Fixed two issues raised by [DeepScan](https://deepscan.io/dashboard/#view=project&tid=16023&pid=19250&bid=524130&subview=pull-request&prid=1074174).
> fix potential NPE in `toDataURL` function in the legacy SVG renderer. remove unused import.

- src/graphic/helper/roundSector.ts
- test/sector.html
This fixes apache/echarts#16385.
> fix(sector): fix some broken cases caused by precision.

- src/graphic/helper/roundSector.ts
- test/sector.html
In #870, we fixed the animation bug caused by the `NaN` value. But that only works in canvas renderer. In SVG renderer, the path can't be successfully built because of the `NaN` value.
The related test case is the same as #870, that is, the last test case in echarts/test/pie-animation.html
> fix(sector): fix a case in which the angle is NaN.

- src/svg/graphic.ts
The vnode `svgElement` may be shared by multiple patterns because the cache strategy in https://github.com/apache/echarts/blob/master/src/util/decal.ts#L121. It may cause render issue like described in https://github.com/apache/echarts/issues/16449. This PR clones the svgElement to make sure each vnode is unique.
> fix(svg): fix shared vnode in pattern brings render issue

- index.d.ts
The type should not point to the source code, which will cause the upper layer to rely on the compilation type to report an error
#724
> Update index.d.ts #724

- src/graphic/helper/image.ts
> fix: 修复createOrUpdateImage方法image实例丢失的问题

- src/canvas/helper.ts
#898 tries to fix the problem of invalid input with gradients but it seems to get wrong results when checking if a number is safe. It caused all gradients to break down in Apache ECharts.
I also tested with the case of https://github.com/apache/echarts/issues/16649 and #898 's fixing didn't work but after this PR's fixing it works.
> fix(gradient): #898 has bug about safe checkingand breaks all gradients

- src/tool/color.ts
- test/ut/spec/tool/color.test.ts
解析rgb颜色时能兼容处理 rgb(2,163,254,1)格式
> fix: parse rgb but gives rgba value

- src/core/dom.ts
- src/svg/core.ts
Fix apache/echarts#17399
Since we don't encode the SVG string, the generated SVG may be broken if it contains special characters.
And the `encodeHTML` function was moved from `echarts` to `zrender` in this PR.
> fix(svg): encode HTML when converting vnode to string.

- src/canvas/Layer.ts
- test/pattern-transform.html
When setting an image as the background color, the canvas renderer doesn't scale it by the device pixel ratio, which results in the pattern effect being different from the effect in the SVG renderer.
| Before | After |
| :----: | :----: |
| ![image](https://user-images.githubusercontent.com/26999792/180654538-59c7aea5-3ff5-47bb-8eb1-25116a60a1b9.png) | ![image](https://user-images.githubusercontent.com/26999792/180654491-12bf478c-da91-4b5c-8242-090ea2d01397.png) |
Note that the size of the background image is _180px×180px_ 👆
> fix(canvas): fix pattern is not correctly scaled in canvas renderer

- src/Handler.ts
- src/core/event.ts
- src/graphic/Displayable.ts
- src/zrender.ts
- test/coarse-pointer.html
- test/lib/config.js
- test/lib/testHelper.js
This PR is intended to increase elements' responsive area on mobile devices so that elements can be touched more easily.
The idea is inspired by W3C's [Understanding Success Criterion 2.5.5: Target Size](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html).
The algorithm can be briefly described as:
1. Find the hovering element at the pointer position. If it exists, return the hovering element. Otherwise, go to 2.
2. Calculate the elements whose bounding boxes have intersection with the touch position enlarged by "pointerSize" (which is 44px by default)
3. Loop through different radius and angle from the pointer position to check if there are elements intersecting with it.
For cases that have too many elements, this feature can be turned off by setting `ignoreCoarsePointer` to …
> Feature: coarse pointer tolerance

- src/core/util.ts
Related to the discussion in https://github.com/ecomfe/zrender/issues/965
This PR is lacking tests, if the general direction is ok and validated, I will add the relevant tests.
From initial benchmarks
```
> node src/core/util.benchmark.js
cpu: Apple M1 Pro
runtime: node v18.3.0 (arm64-darwin)
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
• n=8
------------------------------------------------- -----------------------------
Native      92.59 ns/iter  (88.37 ns … 521.94 ns)  94.09 ns  116.1 ns 131.65 ns
Polyfill   140.06 ns/iter (137.22 ns … 171.45 ns) 139.03 ns 164.76 ns 170.73 ns
summary for n=8
Native
1.51x faster than Polyfill
• n=32 …
```
> feat(polyfill): use native map if available

- .github/workflows/nightly-next.yaml
After analyzing the logs, I found the failure will generally occur when the two versions (main & next) are published at the nearly same time. So this PR tries to delay one of the versions for 10 minutes.
> chore(nightly-build): fix potential npm publish error due to time conflict

- src/core/platform.ts
- test/ssr-measureText.html
- test/ut/spec/core/platform.test.ts
Fix #947
Fix apache/echarts#17326
The font string might be composed as `normal normal 12px sans-serif` via the [`Text#makeFont`](https://github.com/ecomfe/zrender/blob/master/src/graphic/Text.ts#L894) function. So the `^` and `$` should be removed from the expression.
| Before | After |
| :----: | :----: |
| ![image](https://user-images.githubusercontent.com/26999792/197518664-d7a7d757-02bd-457e-9555-07f00b14c44a.png) | ![image](https://user-images.githubusercontent.com/26999792/197518616-e95411fc-4972-43a2-b916-1686fc1161eb.png) |
> fix(platformApi): fix wrong expression for extracting the font size

- src/svg/graphic.ts
Rebuild path when an element has no path.
\- This fixes the shape may disappear after the morphing animation is finished in the SVG renderer.
See also `test/universalTransition2.html` for reproduction.
| Before | After |
| :-----: | :-----: |
| ![BA](https://user-images.githubusercontent.com/26999792/204037337-19eaa2d0-c0cd-4c30-90d6-d60c9aa1bb6c.gif) | ![AA](https://user-images.githubusercontent.com/26999792/204037643-e7608869-ed50-4df0-8d32-f993fe505a85.gif) |
| ![BB](https://user-images.githubusercontent.com/26999792/204037955-79f55c29-0702-4d1d-942b-cfc638dff192.gif) | ![AB](https://user-images.githubusercontent.com/26999792/204037946-d0234283-685a-46de-94df-85d3fca5a224.gif) |
> fix(morph): fix shape may disappear after morphing animation is finished in SVG renderer

- src/graphic/helper/parseText.ts
fix apache/echarts#17941
Charsets like Cyrillic should break work the same as Latin.
[Unicode Character Ranges](https://jrgraphix.net/research/unicode_blocks.php)
> fix: Charsets like Cyrillic should break work the same as Latin

- src/svg/core.ts
#935 encodes all tags but does not exclude the `style` tag, which causes the defined CSS section not to work.
> fix(svg): fix unexpected encoding for `style` tag

- package-lock.json
- package.json
- src/zrender.ts
When releasing ZRender 5.4.2, I forgot to run `npm run release` before `npm publish` so that the version number in `'lib'` is not correct. So we need to release a new version 5.4.3.
> chore: release 5.4.3

- build/prepublish.js
- package.json
According to recent mistakes in publishing to npm, sometimes some files neither tracked by git nor ignored by the `.npmignore` file are unexpectedly published [1], and more often, the versions in different files are inconsistent [2][3], which is more serious than the former. Therefore, I've added a script `build/prepublish.js` that runs before really publishing distribution files to npm to reduce the possibility of this kind of mistake.
> [1] [`1.log`](https://cdn.jsdelivr.net/npm/echarts@5.4.0/1.log) was published to npm in Apache ECharts v5.4.0
> [2] Published v5.4.2 but [the version in `lib/zrender.js`](https://cdn.jsdelivr.net/npm/zrender@5.4.2/lib/zrender.js) is still `5.4.1`
> [3] Published v5.3.1 but both [the version in `lib/zrender.js`](https://cdn.jsdelivr.net/npm/zrender@5.4.2/l …
> chore: fix deprecated npm script & add check for version and unexpected files before publishing to npm

- src/core/Transformable.ts
Resolves apache/echarts#18412. See apache/echarts#18625 for the test case.
When checking the hovering target, the [`Transformable#transformCoordToLocal`](https://github.com/ecomfe/zrender/blob/5.4.3/src/core/Transformable.ts#L257-L264) function will be used in the [`Displayable#rectContain`](https://github.com/ecomfe/zrender/blob/5.4.3/src/graphic/Displayable.ts#L264-L268) function.
But in the [`Transformable#updateTransform`](https://github.com/ecomfe/zrender/blob/5.4.3/src/core/Transformable.ts#L105-L113) function, the `invTransform` is not reset when the `transform` is set to the identity matrix, which may result in a wrong local coordinate.
> fix(transform): fix `invTransform` may not be reset when updating transform

- src/svg/patch.ts
Fixes https://github.com/apache/echarts/issues/16610
This pull request addresses a specific limitation concerning [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). When CSP is enabled, direct assignments to an element's style property using a string are disallowed. However it is possible to use `element.style.cssText = ...` instead.
Create and open an HTML file with the following content:
```
<!DOCTYPE html>
<html>
<head>
<meta
http-equiv="Content-Security-Policy"
content="script-src 'nonce-my-nonce'; style-src 'nonce-my-nonce'"
/>
<style nonce="my-nonce">
#main {
width: 100vw;
height: 100vh;
}
</style>
</head>
<body>
<div id="main"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/zrender/5.4.4/zrender.min.js" nonce="my-nonce"></script> …
```
> fix(svg): fix assigning style attribute does not work when CSP is enforced

- src/canvas/Layer.ts
- src/canvas/Painter.ts
As we discussed before, some extension libraries may create their own `Layer` for customization via [`Painter#insertLayer`](https://github.com/ecomfe/zrender/blob/5.4.4/src/canvas/Painter.ts#L562-L627) and probably won't inject the `painter` property into the canvas painter like [`echarts-gl`](https://github.com/search?q=repo%3Aecomfe%2Fecharts-gl%20insertLayer&type=code) and [`echarts-for-weixin`](https://github.com/ecomfe/echarts-for-weixin) [1], this results in [a potential NPE in the canvas pattern dirty callback handler](https://github.com/ecomfe/zrender/blob/5.4.4/src/canvas/Layer.ts#L454).
So it's better to remove the redundant `__painter` from `Layer` to reuse the existing `painter` property and inject `painter` in `Painter#insertLayer` when it doesn't exist.
[1] Error threw in …
> fix(canvas): fix potential NPE in canvas pattern dirty callback handler

- package.json
When I use vite, the internal call to the 'registerPainter' method will be treeshaking.
> fix: add `lib/all.js` to sideEffects

- src/core/matrix.ts
- src/tool/parseSVG.ts
- test/ut/spec/core/matrix.test.ts
This PR fixes the issue #1033 and specifically [echarts/19141](https://github.com/apache/echarts/issues/19141).
It adds the possibility to provide pivot coordinates around which to rotate the matrix.
If documentation updates are required, could you please assist me with it? The documents are in Chinese, and I don't understand the language.
> feat(matrix): allow rotating relative to a point different than the origin

- src/core/env.ts
This PR improves the detection of nodejs version 21.1.0 and above
> fix(env): fix env detection compatibility in node v21.1.0

- src/Element.ts
- src/svg/Painter.ts
- src/svg/core.ts
- src/svg/cssAnimation.ts
- src/svg/cssClassId.ts
- src/svg/cssEmphasis.ts
- src/svg/graphic.ts
- src/tool/color.ts
- src/zrender.ts
- test/svg-meta-data.html
> feat(ssr): add emphasis style in ssr css apache/echarts#18334

- src/canvas/Layer.ts
- src/svg/Painter.ts
- test/svg-backgroundColor.html
Fix apache/echarts#18194 where the background rect of svg charts are all having the same `id="0"`.
> fix(svg): duplicate id for background rect with multiple charts

- src/zrender.ts
A chart is performing certain operations. After the operation, it will be refreshed and calling flush. At this time, the instance has been disposed, an error will appear. such this [issue](https://github.com/ecomfe/zrender/issues/904) and in react native echart [issue](https://github.com/wuba/react-native-echarts/issues/92)
> fix: avoid errors when executing unfinished operations after dispose

- src/svg/graphic.ts
- src/zrender.ts
> fix(svg): skip to set SSR attributes with `undefined` values

- src/graphic/helper/parseText.ts
This PR brings some type tweaks for the parameters of the function `truncateText`.
Resolves apache/echarts#19447
> fix(type): make the last two parameters `ellipsis` & `options` of the function `truncateText` optional

- package.README.md
- package.json
Fix: 
1. fix that some old version bundler (like rollup) do not recognize wildcard that not at the end of the patter string (e.g. "exports: {"./*.js": "xxx"}"). 
2. Add readme to package.json.
See details in #1051
> Fix package.json exports

- .github/workflows/nightly-next.yaml
- .github/workflows/nightly.yaml
The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v4
* update [`actions/setup-node`](https://github.com/actions/setup-node) to v4
Still using the older versions of these actions will generate several warnings in CI runs, for example in https://github.com/ecomfe/zrender/actions/runs/7692866561:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The PR will get rid of those warnings.
> chore(workflow): update actions/checkout + actions/setup-node to v4

- README.md
According to [ASF policy](https://www.apache.org/foundation/marks/faq/#attribution), we need to add this attribution.
> Add attribution of Apache marks

- src/core/platform.ts
I am using echarts in a react native environment.
Which uses rem adaptation, so a similar code appears
fontSize: rem(12) => fontSize: 11.5
I found a problem.When fontSzie is set to decimal it causes some rendering exceptions.
After troubleshooting I found out that it is an issue with a regularity in measureText in zrender. This regular expression was causing abnormal behavior when parsing decimals.
> fix(platform): fix `measureText` can't recognize decimal font size

- src/svg/Painter.ts
- src/svg/core.ts
- src/svg/graphic.ts
See https://github.com/apache/echarts/issues/15029#issuecomment-2099531410
> fix(svg): set `pointer-events` as `visible` when fill/stroke color `none` in SSR mode & fix invalid `transparent` color issue

- .npmignore
Similar to apache/echarts#19695 but the `src` folder is reserved since ECharts will import the source code from this folder.
> chore: exclude some unused dirs and files when publishing to npm

- .npmignore
#1085 excluded the whole `build` folder from npm package, which is imported by echarts and causes the echarts package to fail to publish. So this PR is to add this folder back.
[1] https://github.com/apache/echarts/actions/runs/9971316886/job/27552144963#step:4:59
[2] https://github.com/apache/echarts/blob/master/build/pre-publish.js#L42
> chore: still publish `build` folder to npm as echarts needs it

- src/core/PathProxy.ts
- src/tool/path.ts
When providing the ability to support `compoundPath` for custom series in Apache ECharts, I found that only the last path data is rendered in a compundPath. This is cause by calling `setData` instead of `appendData` in Path.
> fix(path): using appendData instead of setData for path

- package-lock.json
- package.json
Along with https://github.com/apache/echarts/pull/20485, this allows users to select their own version of tslib (without having to resort to resolutions to force it).
> Relax tslib requirement specifier

- package-lock.json
- package.json
Revert #1097 due to compatibility consideration after discussing with other committers. We may consider upgrading it in v6.
> chore: revert tslib version

- src/graphic/Text.ts
- test/text-overflow.html
Current behavior: Hovering mouse over an axis label should have a click target that is aligned with the axis label text. Click target is where mouse pointer is hovering in the screenshot.
This PR fix it.
Original bug issue: apache/echarts#18306 .
And ecomfe/zrender#1091 located the problematic code successfully (thanks @linghaoSu , it's helpful). But the fix was not entirely correct.
Memo info: This code used to be modified in commits bd2642ec54eb3932a88012d559e92d3d956d6f0f and bd2642ec54eb3932a88012d559e92d3d956d6f0f , where the `boundingRect.width` was modified from `style.width` to `innerWith` and then `outerWith`, but the `boundingRect.x` was not modified correspondingly.
zrender/test/text-overflow.html
Set in the config panel:
+ `overflow: 'truncate'` 
+ `align: 'center'` 
+ uncheck …
> fix: `boundingRect.x` of text is incorrect when `overflow: 'truncate'`.

- src/graphic/Text.ts
- src/graphic/helper/parseText.ts
- test/text-overflow.html
support output the state `isTruncated` in `Text` element, which can be used in the upper program like echarts tooltip, as required by apache/echarts#16315 .
Test case: 
test/text-overflow.html
> feat: support output the state `isTruncated` in `Text` element.

- src/core/PathProxy.ts
- src/tool/path.ts
#1096 changes `path.setData(pathProxy.data);` into `path.appendPath(pathProxy);` to support compoundPath but it causes appending path data for unexpected multiple times (see demo at echarts/test/geo-svg-demo.html).
This PR reverts the changes and I will find another way to support compoundPath later.
> fix(path): revert #1096 to be path.setData

- src/core/env.ts
The React Native test environment *is* Node but sets up a window global: https://github.com/facebook/react-native/blob/7a85b911254dbae9fac4c6d8a862a20c33e0b36a/packages/react-native/Libraries/Core/setUpGlobals.js#L18
Reintroduce the navigator.userAgent check as a fallback for detecting a Node environment
> fix(env): improve env detection compatibility for Node

- src/tool/color.ts
- src/tool/parseSVG.ts
- test/parser-svg-stop-opacity.html
Fix (partially) https://github.com/apache/echarts/issues/18407#issuecomment-2738836773
| Before | After |
| :----: | :----: |
| ![image](https://github.com/user-attachments/assets/fabf3e92-2a15-46cf-812a-3b17477ec47a) | ![image](https://github.com/user-attachments/assets/4208de3e-b42b-414e-83e4-4040cc723fee) |
> fix(svg): fix `stop-opacity` is not parsed by SVG parser

- src/tool/color.ts
Support function for modifyHSL so that we can calculate dark theme color in ECharts from light color.
> feat(color): support  function for modifyHSL

- src/contain/text.ts
- src/graphic/TSpan.ts
- src/graphic/Text.ts
- src/graphic/helper/parseText.ts
- test/text.html
Previously, plain text bounding rect is inconsistent (contain stroke width or not) according to style.width & style.overflow (even if no wrapping or truncation happen and text is visually the same). This commit makes it consistent. 
Previously, the bounding rect varies and unpredictable according to the internal auto-stroke application:
+ If auto stroke is applied, there are 1px extra stroke, otherwise not. It's discernible and matters in compact layout of multiple labels.
+ plain text: if `style.width` & `style.overflow` are specified, exclude stroke, otherwise include stroke.
+ rich text: always exclude stroke
This commit exclude auto-stroke width uniformly, since auto-stroke using the same color as background to make the border invisible. 
Should text bounding rect includes text stroke …
> Fix text bounding rect
