src/core/BoundingRect.js
替换zrender文件路径为相对路径:
'zrender/core/vector' => './vector'
'zrender/core/matrix' => './matrix'
=> fix path error

src/svg/graphic.js
参考的
http://stackoverflow.com/questions/9281199/adding-text-to-svg-document-in-javascript
=> 修改用svg在android手机上添加文字显示不出来的问题

src/Handler.js, src/dom/HandlerProxy.js
Enable multi-touch for ECharts in wechat app.
=> feat: expose processGesture api for wechat app

README.md
￼![image](https://user-images.githubusercontent.com/779050/52845305-bde44600-3141-11e9-900e-53682d444c37.png)
=> docs: add badge in readme

src/contain/text.js, src/graphic/Text.js, src/svg/graphic.js, src/vml/graphic.js
(24b8be4a9b1a1720cbbc8c423da7f9a9d413cd98 and 1bf50b4ffadc6214d6e5abe0f47d5a880c64f56a).
And tiny tweak code style.
=> fix: rich text getBoundingRect error brought by previous commit

package-lock.json, package.json
- Add `package-lock.json`
- Used `npm audit fix` to upgrade some npm package versions
- Changed license name according to https://spdx.org/licenses/
=> chore: add package lock and fix audit

src/graphic/helper/text.js, src/svg/graphic.js
apache/incubator-echarts#10732
SVG truncate logic aligns with Canvas.
=> fix(svg): text truncate bug with treemap

src/svg/Painter.js, src/svg/helper/GradientManager.js
fix(svg): rectText text color when rect has gradient apache/incubator-echarts#11036
This is a bug when rectText has gradient and text will use the gradient as text fill color when updates.
=> fix(svg): rectText text color when rect has gradient

src/graphic/Displayable.js, src/graphic/helper/text.js
+ fix code annotation
+ export getBoxPosition()
=> Add feat for minBI

src/svg/helper/ClippathManager.js
Otherwise, Safari has compatibility problem
=> fix(svg): use lower case for clippath

src/Painter.js
Fixed issue https://github.com/apache/incubator-echarts/issues/12042
=> fix element may drawn in the wrong layer when using incremental in multiple layers

src/canvas/graphic.ts, src/graphic/Text.ts, src/svg/graphic.ts
For apache/incubator-echarts#12961.
=> feat: support for dash line scale. 

src/Element.ts, src/core/WeakMap.ts, src/graphic/Displayable.ts
See also: https://github.com/apache/incubator-echarts/pull/13522
=> Fix: clarify the done/aborted of animateTo.

src/core/arrayDiff.ts, src/debug/showDebugDirtyRect.ts, src/graphic/helper/smoothBezier.ts, src/graphic/helper/smoothSpline.ts, src/tool/transformPath.ts
Related PR in ECharts https://github.com/apache/incubator-echarts/pull/13563
This change is mainly for bundling dts.
=> fix(type): add name of exported default function

src/core/util.ts
Not only for IE, but thanks to IE.
=> fix(util): `logError` needs a `this` target.

index.js
Fix https://github.com/ecomfe/zrender/issues/677, https://github.com/ecomfe/zrender/issues/676
=> fix: remove-vml-in-entry

index.js
fix https://github.com/ecomfe/zrender/issues/703
=> fix: remove unexpected vml import

src/core/Eventful.ts, src/core/Transformable.ts, src/core/types.ts, src/core/util.ts, src/debug/showDebugDirtyRect.ts, src/zrender.ts
This PR fixes some type errors. And make callback param not always optional. Which is not convenient in strict mode.
=> fix(type): event callback param not always optional

src/graphic/Text.ts
related to https://github.com/apache/echarts/pull/14214
=> chore: add `none` to `textStyle` `overflow`

index.js, src/canvas/Layer.ts, src/graphic/Gradient.ts
fix https://github.com/apache/echarts/issues/14354
=> fix unnecessary requirement in CanvasGradientObject. fix canvas painter not included in build

src/animation/Animator.ts
=> fix(animation/Animator): add NaN check

src/canvas/graphic.ts
Fix https://github.com/apache/echarts/issues/14536
=> fix: CanvasPatttern#setTransform may not exists apache/echarts#14536

src/Element.ts, src/graphic/Displayable.ts, src/graphic/Text.ts
Fix https://github.com/apache/echarts/issues/14841
Also, fix an issue that text may not render caused in https://github.com/ecomfe/zrender/pull/754
=> fix(text): fix gradient text background cause rendering error

src/core/Transformable.ts, src/tool/parseSVG.ts, test/transform.html
1. Fix skew matrix calculation in SVG parser.
2. Fix skew in decomposition.
3. FIx skew in transform calculation(y-axis is inversed.
=> fix(transform): fix skew

src/canvas/Layer.ts, src/core/util.ts
fix type error in https://github.com/ecomfe/zrender/pull/759
=> fix wrong type of pattern object

package-lock.json, package.json
Update typescript version to latest
=> chore: update ts version

.github/workflows/nightly-next.yaml, build/prepareNightly.js, package.json
Features of the next minor/major version will be included in the next branch before it's merged into master
=> add nightly publish for next branch

src/mixin/Draggable.ts
Currently drag is not working when u drag Element's textContent. This pr should fix it.
Related: apache/echarts#15428
=> fix(draggable): draggable not working on Element's textContent

src/canvas/graphic.ts, src/graphic/Text.ts, src/graphic/helper/parseText.ts, src/graphic/shape/Circle.ts
Support contentWidth for plainText so that apache/echarts#16034 could do the calculation.
=> fix(text): rich text overflow

build/processLib.js, build/transformImport.js
Case:
```ts
import {
AAAA,
// BBB
} from 'module-10';
import {
normalizeToArray
// , MappingExistingItem, setComponentTypeToKeyInfo, mappingToExists
} from '../util/model';
```
=> fix parsing named import with comment

package.json
=> chore: update the description and keywords in package.json

package-lock.json, src/animation/Animator.ts
Line width was larger than 120.
=> style: fix lint error with line width

.github/workflows/nightly-next.yaml, .github/workflows/nightly.yaml
=> chore: update deprecated Node v12 to v16 & update action dependency version

src/core/util.ts
Add `hasKey` method into `HashMap` for ECharts. See also apache/echarts#17861.
=> feat(util): add `hasKey` method into `HashMap` for ECharts.

build/package.json, dist/package.json, package.json, src/.eslintrc.yaml, test/package.json
=> feat: change to default ESM package. For developer testing and node usage in customization module scenario.

src/core/util.ts, src/dom/HandlerProxy.ts
Just fixing a few typos, no functional changes.
=> chore: fix a few typos

src/core/env.ts
=> fix(env): try fixing detection for node environment

src/core/dom.ts
=> fix(dom): add `transformLocalCoordClear` function to clear markers created by `transformLocalCoord`
